((nil . ((indent-tabs-mode . nil)))
 (nix-mode . ((mode . apheleia)))
 (js-mode . ((mode . apheleia)))
 (python-mode . ((mode . apheleia)))
 (css-mode . ((css-indent-offset . 2)))
 (auto-mode-alist . (("\\.html\\'" . markdown-mode))))
