[project]
name = "www"
version = "0.0.0"
description = "Vincent Bernat's website"
authors = [{ name = "Vincent Bernat", email = "vincent@bernat.ch" }]
requires-python = ">=3.10"
dependencies = [
    "Babel==2.*",
    "Pillow",
    "PyPDF2==3.*",
    "Pygments==2.*",
    "invoke",
    "langcodes[data]==3.*",
    "lxml",
    "pyquery==2.*",
    "python-dateutil>=2.8",
    "hyde",
    "pygments-haproxy",
    "pygments-ios",
    "pygments-junos",
    "setuptools",
    "py-spy>=0.4.1",
    "skia-python>=144.0.post2",
    "diskcache>=5.6.3",
    "matplotlib>=3.9.4",
    "emoji>=2.15.0",
]

[tool.uv]

[tool.uv.sources]
hyde = { git = "https://github.com/vincentbernat/hyde", branch = "vbe/master" }
pygments-haproxy = { git = "https://github.com/vincentbernat/pygments-haproxy", rev = "master" }
pygments-ios = { git = "https://github.com/vincentbernat/pygments-ios", rev = "master" }
pygments-junos = { git = "https://github.com/vincentbernat/pygments-junos", rev = "master" }

# The project is empty. We only use the dependencies.
[tool.hatch.build.targets.wheel]
bypass-selection = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
