version = 1

# Labels for custom license identifiers, used by layout/licenses.j2.
[labels]
LicenseRef-Authorized = { en = "used with authorization", fr = "utilisé avec autorisation" }
LicenseRef-Illustration = { en = "used for illustrative purposes", fr = "utilisé à titre d'illustration" }

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "Vincent Bernat"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "content/**/*.html"
SPDX-FileCopyrightText = "Vincent Bernat"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "content/en/extending-xkb.html"
SPDX-FileCopyrightText = "martin f. krafft"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
  "content/fr/blog/2009-separation-privileges-c.html",
  "content/fr/blog/2009-python-reseau.html",
  "content/fr/blog/2010-python-c.html",
  "content/en/blog/2009-privilege-separation-c.html",
  "content/en/blog/2009-python-networking.html",
  "content/en/blog/2010-python-c.html",
]
SPDX-FileCopyrightText = "GNU/Linux Magazine France <https://connect.ed-diamond.com/gnu-linux-magazine>"
SPDX-License-Identifier = "CC-BY-NC-ND-2.0"

[[annotations]]
path = "content/media/css/*.css"
SPDX-FileCopyrightText = "Vincent Bernat"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "content/media/css/2026-spanning-tree.css"
SPDX-FileCopyrightText = "Vincent Bernat"
SPDX-License-Identifier = "GPL-2.0-or-later"
[annotations.note]
en = "with sprites from [Craftpix](https://craftpix.net/) and [Yanin](https://yaninyunus.itch.io/16x16-specialtycoffee)"
fr = "avec des sprites de [Craftpix](https://craftpix.net/) et [Yanin](https://yaninyunus.itch.io/16x16-specialtycoffee)"

[[annotations]]
path = "content/media/css/gallery-upstream.css"
SPDX-FileCopyrightText = "Marek Grzybek"
SPDX-License-Identifier = "MIT"
source = "https://github.com/feimosi/baguetteBox.js"

[[annotations]]
path = "content/media/css/isso-upstream.css"
SPDX-FileCopyrightText = "Martin Zimmermann"
SPDX-License-Identifier = "MIT"
source = "https://github.com/posativ/isso"

[[annotations]]
path = "content/media/css/katex.css"
SPDX-FileCopyrightText = "Khan Academy"
SPDX-License-Identifier = "MIT"
source = "https://github.com/KaTeX/KaTeX"

[[annotations]]
path = "content/media/js/*.js"
SPDX-FileCopyrightText = "Vincent Bernat"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "content/media/js/2026-spanning-tree*.js"
SPDX-FileCopyrightText = "Vincent Bernat"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "content/media/js/gallery.js"
SPDX-FileCopyrightText = "Marek Grzybek"
SPDX-License-Identifier = "MIT"
source = "https://github.com/feimosi/baguetteBox.js"

[[annotations]]
path = "content/media/js/hls.js"
SPDX-FileCopyrightText = "Dailymotion"
SPDX-License-Identifier = "Apache-2.0"
source = "https://github.com/video-dev/hls.js"

[[annotations]]
path = "content/media/js/isso.js"
SPDX-FileCopyrightText = "Martin Zimmermann"
SPDX-License-Identifier = "MIT"
source = "https://github.com/posativ/isso"

[[annotations]]
path = "content/media/files/**"
SPDX-FileCopyrightText = "Vincent Bernat"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "content/media/files/PlanComptable.gnucash"
SPDX-FileCopyrightText = "Autorité des normes comptables <https://www.anc.gouv.fr/>"
SPDX-License-Identifier = "CC-PDM-1.0"
source = "https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000029583307"

[[annotations]]
path = ["content/media/files/lldpd/*", "content/media/files/udpproxy/*"]
SPDX-FileCopyrightText = "Vincent Bernat"
SPDX-License-Identifier = "ISC"

[[annotations]]
path = "content/media/fonts/katex/KaTeX_*"
SPDX-FileCopyrightText = "Khan Academy"
SPDX-License-Identifier = "OFL-1.1"
source = "https://github.com/KaTeX/KaTeX"

[[annotations]]
path = "content/media/fonts/iosevka*"
SPDX-FileCopyrightText = "Belleve Invis"
SPDX-License-Identifier = "OFL-1.1"
source = "https://github.com/be5invis/Iosevka"

[[annotations]]
path = "content/media/fonts/baskerville*"
SPDX-FileCopyrightText = "Pablo Impallari and Rodrigo Fuenzalida"
SPDX-License-Identifier = "OFL-1.1"
source = "https://github.com/impallari/Libre-Baskerville"

[[annotations]]
path = "content/media/fonts/merriweather*"
SPDX-FileCopyrightText = "Eben Sorkin"
SPDX-License-Identifier = "OFL-1.1"
source = "https://github.com/EbenSorkin/Merriweather"

[[annotations]]
path = "content/media/images/**"
SPDX-FileCopyrightText = "Vincent Bernat"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["content/media/images/ducks.gif", "content/media/images/deer.gif"]
SPDX-FileCopyrightText = "Romain Courtois <https://romaincourtois.com/>"
SPDX-License-Identifier = "LicenseRef-Authorized"

[[annotations]]
path = "content/media/images/l/ext--*.svg"
SPDX-FileCopyrightText = "Papirus Development Team <https://github.com/PapirusDevelopmentTeam>"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "content/media/images/akvorado/cover.jpg"
SPDX-FileCopyrightText = "H. Zell"
SPDX-License-Identifier = "CC-BY-SA-3.0"
source = "https://commons.wikimedia.org/wiki/File:Water_wheel_-_Zell_am_Harmersbach_01.jpg"

[[annotations]]
path = "content/media/images/day-planner@2x.jpg"
SPDX-FileCopyrightText = "Fowl Language Comics"
SPDX-License-Identifier = "LicenseRef-Authorized"
source = "https://www.fowllanguagecomics.com/comic/day-planner/"

[[annotations]]
path = "content/media/images/eudyptula.jpg"
SPDX-FileCopyrightText = "Coada Dragos"
SPDX-License-Identifier = "CC-BY-SA-4.0"
source = "https://commons.wikimedia.org/wiki/File:Pinguinul-mic-Eudyptula-minor1-650x519.jpg"

[[annotations]]
path = "content/media/images/frnog.jpg"
SPDX-FileCopyrightText = "Thomon <https://commons.wikimedia.org/wiki/User:Thomon>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
source = "https://commons.wikimedia.org/wiki/File:2_rue_Scribe.jpg"

[[annotations]]
path = "content/media/images/msa-garratt@2x.jpg"
SPDX-FileCopyrightText = "1930 Western Australian Government Railways"
SPDX-License-Identifier = "CC-PDM-1.0"
source = "https://commons.wikimedia.org/wiki/File:Western_Australian_Government_Railways_class_Msa_Garratt_articulated_steam_locomotive_--_elevation_and_plan_drawing.jpg"

[[annotations]]
path = "content/media/images/simpson-s06e18@2x.jpg"
SPDX-FileCopyrightText = "1995 Twentieth Century Fox Television"
SPDX-License-Identifier = "LicenseRef-Illustration"

[[annotations]]
path = "content/media/images/stp-dragonblood@2x.jpg"
SPDX-FileCopyrightText = "Alex38 <https://commons.wikimedia.org/wiki/User:Alex38>"
SPDX-License-Identifier = "CC-BY-4.0"
source = "https://commons.wikimedia.org/wiki/File:Dragonblood_tree_in_Socotra_2.jpg"

[[annotations]]
path = "content/media/images/swinog.jpg"
SPDX-FileCopyrightText = "Mike Lehmann <https://commons.wikimedia.org/wiki/User:Mike_Switzerland>"
SPDX-License-Identifier = "CC-BY-SA-3.0"
source = "https://commons.wikimedia.org/wiki/File:Gurten_4734.jpg"

[[annotations]]
path = "content/media/images/tcp/tcp-state-diagram*.svg"
SPDX-FileCopyrightText = "Ivan Griffin"
SPDX-License-Identifier = "LPPL-1.3c"
source = "https://texample.net/tcp-state-machine/"

[[annotations]]
path = "content/media/images/unreachable-state@2x.png"
SPDX-FileCopyrightText = "XKCD"
SPDX-License-Identifier = "CC-BY-NC-2.5"
source = "https://xkcd.com/2200/"

[[annotations]]
path = "content/media/images/xbmc-eden-logo.jpg"
SPDX-FileCopyrightText = "FiroPyro"
SPDX-License-Identifier = "CC-BY-NC-3.0"

[[annotations]]
path = "content/media/videos/*"
SPDX-FileCopyrightText = "Vincent Bernat"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "content/media/videos/2018-self-hosted-videos*"
SPDX-FileCopyrightText = "caminandes.com"
SPDX-License-Identifier = "CC-BY-3.0"
source = "https://studio.blender.org/projects/caminandes-3/"

[[annotations]]
path = "content/media/videos/2019-self-hosted-videos-subtitles*"
SPDX-FileCopyrightText = "Blender Animation Studio <https://studio.blender.org/>"
SPDX-License-Identifier = "CC-BY-ND-2.0"

[[annotations]]
path = "content/media/videos/2026-spanning-tree*"
SPDX-FileCopyrightText = "Vincent Bernat"
SPDX-License-Identifier = "CC-BY-SA-4.0"
[annotations.note]
en = "with music from [Aaron Dunn](https://www.chosic.com/download-audio/25044/)"
fr = "avec une musique d'[Aaron Dunn](https://www.chosic.com/download-audio/25044/)"

[[annotations]]
path = ["extensions/*.py", "tasks.py", "layout/*.j2"]
SPDX-FileCopyrightText = "Vincent Bernat"
SPDX-License-Identifier = "CC-BY-4.0"
