mode: development
media_root: media
media_url: /media
base_url: /
encode_safe: "/@"
plugins:
  - hyde.ext.plugins.meta.MetaPlugin
  - hyde.ext.plugins.git.GitDatesPlugin
  - extensions.combine.CombinePlugin
  - hyde.ext.plugins.languages.LanguagePlugin
  - hyde.ext.plugins.auto_extend.AutoExtendPlugin
  - hyde.ext.plugins.sorter.SorterPlugin
  - hyde.ext.plugins.tagger.TaggerPlugin
  - hyde.ext.plugins.less.LessCSSPlugin
  - hyde.ext.plugins.textlinks.TextlinksPlugin
  - extensions.css.CSSPrefixerPlugin
  - extensions.images.ImageThumbnailsPlugin
  - extensions.images.ImageFixerPlugin
  - extensions.text.LatexPlugin
  - extensions.text.FootnotesPlugin
  - extensions.typo.TypographyPlugin
context:
  data:
    base: https://vincent.bernat.ch
    languages:
      fr: français
      en: English
meta:
  nodemeta: meta.yaml
  author: Vincent Bernat
  twitter: vince2_
  github: vincentbernat
  title: "MTU Ninja"
  language: en
  share: true
  tags: [unclassified]
  sources: https://github.com/vincentbernat/vincent.bernat.ch
simple_copy:
  - media/videos/**
  - media/files/**
less:
  app: node_modules/less/bin/lessc
markdown:
  extensions:
    - codehilite
    - extra
    - toc
    - extensions.markdown.admonition
    - extensions.markdown.glyphs
    - extensions.markdown.mathjax
    - extensions.markdown.responsive_table
    - extensions.markdown.codehilite_lang
  extension_configs:
    toc:
      permalink: "#"
      # Also modify it in layout/atom.j2
    codehilite:
      guess_lang: false
    extra:
      markdown.extensions.footnotes:
        BACKLINK_TEXT: '&#8617;&#xFE0E;'
  output_format: html5
jinja2:
  filters:
    human_date: extensions.jinja.human_date
    same_tag: extensions.jinja.same_tag
  functions:
    include_file: extensions.jinja.include_file
sorter:
  name:
    attr:
      - relative_path
  time:
    attr:
      - meta.created
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
  time_fr:
    attr:
      - meta.created
      - relative_path
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
      meta.language: fr
  time_en:
    attr:
      - meta.created
      - relative_path
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
      meta.language: en
tagger:
  sorter: time
  tags:
    network:
      descr_en: network
      descr_fr: réseau
      order: 10
    network-bgp:
      descr: BGP
      order: 11
    network-automation:
      descr_en: automation
      descr_fr: automatisation
      order: 12
    network-vxlan:
      descr: VXLAN
      order: 13
    network-vpn:
      descr: VPN
      order: 14
    network-snmp:
      descr: SNMP
      order: 15
    linux:
      descr: Linux
      order: 20
    programming:
      descr_en: programming
      descr_fr: programmation
      order: 30
    programming-go:
      descr: Go
      order: 31
    programming-c:
      descr: C
      order: 32
    programming-python:
      descr: Python
      order: 33
    programming-shell:
      descr: shell
      order: 34
    ssl:
      descr: TLS
      order: 40
    distribution:
      descr: distribution
      order: 50
    distribution-debian:
      descr: Debian
      order: 51
    distribution-nixos:
      descr: NixOS
      order: 52
    retro:
      descr_en: retrocomputing
      descr_fr: rétrocomputing
      order: 60
    web:
      descr: web
      order: 70
    desktop:
      descr_en: desktop environment
      descr_fr: environnement de bureau
      order: 80
    unclassified:
      descr_en: unclassified
      descr_fr: non classé
      order: 999
    outdated:
      descr_en: outdated
      descr_fr: périmé
      order: 1000
