extends: base.j2
default_block: article

language: fr
created: git
modified: git
menu:
  -
     name: "À propos"
     page: "index.html"
  -
     name: "Blog"
     page: "blog"
  -
     name: "Projets"
     page: "projets.html"
l10n:
  otherlinks: "Ailleurs"
  translations: "Aussi disponible en"
  language:
    en: "en anglais"
  comments_nojs: >-
    Le système de commentaire utilise Isso qui nécessite Javascript
  comments: >-
    <a href="#isso-thread">Commentaires</a> (ils reposent sur <em>Isso</em> et sont sans 🍪)
  subscribe: >-
    S’abonner aux mises à jour
  attachments: "Documents liés :"
  tags: "Classé dans"
  share: "Partager cet article"
  share_on: "Partager sur"
  share_by_mail: "Partager par courrier électronique"
  range: "-"                    # trait d'union
  sources: "Sources"
  site: "Site"
  page: "Page"
  history: "Historique"
  edit: "Éditer"
  search: "Recherche"
