---
extends: base.j2
default_block: article

language: fr
locale: fr_FR
created: git
modified: git
menu:
  -
    name: "À propos"
    page: "index.html"
  -
    name: "Blog"
    page: "blog"
  -
    name: "Projets"
    page: "projets.html"
l10n:
  otherlinks: "Ailleurs"
  translations: "Aussi disponible en"
  language:
    en: "en anglais"
  comments_nojs: >-
    Le système de commentaire utilise Isso qui nécessite JavaScript
  comments: >-
    <a href="#isso-thread">Commentaires</a>
    (ils reposent sur <em>Isso</em> et sont sans 🍪)
  no_comments: Les commentaires sont désactivés
  subscribe: >-
    S’abonner aux mises à jour
  attachment: "Document lié :"
  attachments: "Documents liés :"
  tags: "Classé dans"
  range: "-"                    # trait d'union
  sources: "Sources"
  site: "Site"
  page: "Page"
  history: "Historique"
  edit: "Éditer"
  search: "Recherche"
  reading_time:
    - "{} minute de lecture"
    - "{} minutes de lecture"
  words: "{} mots"
  share: "Partager sur"
  share_app:
    - avec une
    - application
  share_email:
    - par
    - courriel
  noai: "Sans recours à l'IA"
ai_usage:
  default: "🧠"
  "Corrections": "🧠"
  "Révision": "✨"
  "Traduit": "🤖"
