extends: base.j2
default_block: article

language: en
created: git
modified: git
menu:
  -
     name: "About"
     page: "index.html"
  -
     name: "Blog"
     page: "blog"
  -
     name: "Projects"
     page: "projects.html"
l10n:
  otherlinks: "Elsewhere"
  translations: "Also available in"
  language:
    fr: "in French"
  comments_nojs: >-
    The comment system uses Isso and requires Javascript
  comments: >-
    <a href="#isso-thread">Comments</a> (they rely on <em>Isso</em> and are 🍪-free)
  subscribe: >-
    Subscribe to new posts
  attachments: "Attachments:"
  tags: "Filed under"
  share: "Share this article"
  share_on: "Share on"
  share_by_mail: "Share by mail"
  range: "–"                    # en dash
  sources: "Sources"
  site: "Site"
  page: "Page"
  history: "History"
  edit: "Edit"
  search: "Search"
