extends: base.j2
default_block: article

language: en
menu:
  -
     name: "Résumé"
     page: "cv.html"
  -
     name: "Projects"
     page: "projects.html"
  -
     name: "Blog"
     page: "blog/"
l10n:
  search: "Search"
  otherlinks: "Other stuff"
  translations: "Other languages"
  posts: "Other articles"
  next: "Next"
  previous: "Previous"
  comments: "View or add a new comment (with Disqus)"
  attachments: "Attachments"
  tags: "Tags"
  share: "Share"
